import { StyleSheet } from 'react-native';

export const sharedStyles = StyleSheet.create({
	// Common message styles
	msgWrap: {
		marginBottom: 12,
		maxWidth: '88%',
		borderRadius: 20,
		borderBottomLeftRadius: 6,
		paddingVertical: 12,
		paddingHorizontal: 16,
		overflow: 'hidden',
		// Ensure message doesn't exceed available height
		maxHeight: '80%',
		flexShrink: 1,
	},
	msgAI: {
		alignSelf: 'flex-start',
		backgroundColor: '#f1f5f9',
		borderColor: '#e2e8f0',
		borderWidth: 1,
		maxWidth: '95%',
	},
	msgUser: {
		alignSelf: 'flex-end',
		backgroundColor: '#2a89f7',
		borderBottomLeftRadius: 20,
		borderBottomRightRadius: 6,
		shadowColor: '#000',
		shadowOpacity: 0.1,
		shadowRadius: 4,
		shadowOffset: { width: 0, height: 2 },
		elevation: 2,
	},
	msgText: {
		fontSize: 14,
		lineHeight: 24,
		fontWeight: '500',
		flexWrap: 'wrap',
		flexShrink: 1,
	},
	msgTextUser: { color: '#fff', fontWeight: '600' },
	msgTextAI: { color: '#0f172a', fontWeight: '500' },
	msgTimeUser: {
		fontSize: 11,
		color: '#ffffff',
		alignSelf: 'flex-end',
		fontWeight: '500',
	},
	msgTimeAI: {
		fontSize: 11,
		color: '#94a3b8',
		alignSelf: 'flex-start',
		fontWeight: '500',
	},

	// Common prompt styles
	promptsTitle: {
		fontSize: 16,
		fontWeight: '700',
		color: '#1e293b',
		marginBottom: 16,
		textAlign: 'center',
	},
	promptsGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		justifyContent: 'center',
	},
	promptCard: {
		minWidth: '45%',
		maxWidth: '48%',
		backgroundColor: '#f6f6f6',
		borderRadius: 12,
		padding: 12,
		borderWidth: 1,
		borderColor: '#e2e8f0',
		shadowColor: '#000',
		shadowOpacity: 0.08,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 4 },
		elevation: 4,
		borderBottomLeftRadius: 6,
		alignItems: 'center',
		justifyContent: 'center',
		flex: 1,
	},
	promptText: {
		fontSize: 12,
		fontWeight: '600',
		color: '#374151',
		lineHeight: 16,
		textAlign: 'center',
		flexWrap: 'wrap',
		flexShrink: 1,
	},
});
